project:
  type: website

website:
  title: "LOGEMP-20-05-2023"
  navbar:
    left:
      - href: LOGEMP-20-05-2023.qmd
        text: Home
      - Sobre.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



